spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ''
    username: wizwolf
    password: wizwolf
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/wizwolf
      connection-timeout: 10000
      idle-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      connection-test-query: select 1

  jpa:
    show-sql: true
    thymeleaf:
      cache: false

  data:
    jpa:
      repositories:
        enabled: true

  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration


  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterAccess=10m, refreshAfterWrite=5m



  messages:
    encoding: utf-8
    basename: i18n/login,i18n/message
logging:
  level:
    root: INFO
ini:
  value1: yourValue1
  value2: yourValue2